name: "Backup Watcher"
version: "2.0.0"
slug: "backup_watcher"
description: "Watch new backups created and sync to remote server via FTPs (implicitly or explicitly, not requiring SFTP)"
url: "https://github.com/th23x/th23-backup-watcher"
arch:
  - aarch64
  - amd64
init: false
homeassistant_api: true
map:
  - type: backup
    read_only: true
  - type: addon_config
    read_only: true
boot: auto
startup: application
options:
  allow_unencrypted_backups: false
  ftps_host: ""
  ftps_port: 21
  ftps_user: ""
  ftps_password: ""
  ftps_implicit: false
  ftps_verify_cert: true
  ftps_ca_file: ""
  ftps_check_hostname: true
  ftps_remote_dir: "backups"
  ftps_sync_deletions: false
  ftps_atomic_upload: true
schema:
  allow_unencrypted_backups: bool
  ftps_host: 'match(^(\[[0-9A-Fa-f:.]+\]|[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*)?\Z)'
  ftps_port: port
  ftps_user: 'match(^[^\x00-\x1f\x7f]{0,128}\Z)'
  ftps_password: password
  ftps_implicit: bool
  ftps_verify_cert: bool
  ftps_ca_file: 'match(^([A-Za-z0-9_][A-Za-z0-9._-]{0,100})?\Z)?'
  ftps_check_hostname: bool
  ftps_remote_dir: 'match(^((?!.*(?:^|/)\.\.(?:/|\Z))[^\x00-\x1f\x7f/][^\x00-\x1f\x7f]{0,254})?\Z)'
  ftps_sync_deletions: bool
  ftps_atomic_upload: bool?
